### ISSUE TITLE
Surface blending service dies

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial-attic/godel#38]
I tested godel on different hardware configurations and on one configuration the node always crashes at start:

```
[surface_blending_service-2] process has died [pid 26385, exit code -11, cmd /home/meulage/catkin_ws/devel/lib/godel_surface_detection/surface_blending_service __name:=surface_blending_service __log:=/home/meulage/.ros/log/1b7dbaac-97dc-11e4-9637-7446a09160eb/surface_blending_service-2.log].
log file: /home/meulage/.ros/log/1b7dbaac-97dc-11e4-9637-7446a09160eb/surface_blending_service-2*.log

```

[logs](https://mega.co.nz/#!VUMhlbzZ!Cx68dR4FuyN7wLgKIenKTSA2PUBmDYvOqkZlIVBBA3o)
## Hardware

```
HP Compact Elite 8300
Motherboard: Asus Intel Q77
CPU: Intel i5 3470
RAM:  8 Go
GPU: NVidia Quadro K600
Storage: Samsung 830 (SSD)
```

Any idea why this happens?

**Comment by shaun-edwards** [comment]
@VictorLamoine, I need some more info.  Which node crashes?  What log message is output to the terminal (it's easier to parse this message than the log files you attached).

**Comment by VictorLamoine** [comment]
Here is a `stdout` log example, the node `surface_blending_service` is crashing; RViz is launching but the `RobotBlendingPanel` panel is grayed out

```
meulage@HP-Compaq-Elite-8300-MT:~$ roslaunch godel_surface_detection robot_blending.launch
... logging to /home/meulage/.ros/log/ed99168c-9bcc-11e4-8dc4-7446a09160eb/roslaunch-HP-Compaq-Elite-8300-MT-2344.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://HP-Compaq-Elite-8300-MT:58167/

SUMMARY
========

PARAMETERS
 * /controller_joint_names: ['joint_s', 'join...
 * /initial_joint_state: [-1.34, 1.008, 0....
 * /mongo_wrapper_ros_HP_Compaq_Elite_8300_MT_2344_2433150109357235812/database_path: /home/meulage/cat...
 * /mongo_wrapper_ros_HP_Compaq_Elite_8300_MT_2344_2433150109357235812/overwrite: False
 * /move_group/allow_trajectory_execution: True
 * /move_group/allowed_execution_duration_scaling: 1.2
 * /move_group/allowed_goal_duration_margin: 0.5
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'action_ns': 'j...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/manipulator/planner_configs: ['SBLkConfigDefau...
 * /move_group/manipulator_asus/longest_valid_segment_fraction: 0.05
 * /move_group/manipulator_asus/planner_configs: ['SBLkConfigDefau...
 * /move_group/manipulator_asus/projection_evaluator: joints(joint_s,jo...
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/start_state_max_bounds_error: 0.1
 * /point_cloud_generator_node/frame_id: world_frame
 * /point_cloud_generator_node/point_cloud_descriptions: [{'h': 0.0, 'rx':...
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/manipulator/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/manipulator/kinematics_solver_attempts: 40
 * /robot_description_kinematics/manipulator/kinematics_solver_search_resolution: 0.01
 * /robot_description_kinematics/manipulator/kinematics_solver_timeout: 0.5
 * /robot_description_kinematics/manipulator_asus/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/manipulator_asus/kinematics_solver_attempts: 40
 * /robot_description_kinematics/manipulator_asus/kinematics_solver_search_resolution: 0.01
 * /robot_description_kinematics/manipulator_asus/kinematics_solver_timeout: 0.5
 * /robot_description_planning/joint_limits/joint_b/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_b/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_b/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_b/max_velocity: 1.0
 * /robot_description_planning/joint_limits/joint_e/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_e/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_e/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_e/max_velocity: 1.0
 * /robot_description_planning/joint_limits/joint_l/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_l/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_l/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_l/max_velocity: 2.0
 * /robot_description_planning/joint_limits/joint_r/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_r/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_r/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_r/max_velocity: 3.0
 * /robot_description_planning/joint_limits/joint_s/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_s/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_s/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_s/max_velocity: 1.0
 * /robot_description_planning/joint_limits/joint_t/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_t/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_t/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_t/max_velocity: 4.0
 * /robot_description_planning/joint_limits/joint_u/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint_u/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint_u/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint_u/max_velocity: 2.5
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.10
 * /surface_blending_service/blending_plan/approach_spd: 0.005
 * /surface_blending_service/blending_plan/blending_spd: 0.01
 * /surface_blending_service/blending_plan/discretization: 0.0025
 * /surface_blending_service/blending_plan/margin: 0.001
 * /surface_blending_service/blending_plan/min_boundary_length: 0.03
 * /surface_blending_service/blending_plan/overlap: 0.0
 * /surface_blending_service/blending_plan/retract_spd: 0.02
 * /surface_blending_service/blending_plan/safe_traverse_height: 0.05
 * /surface_blending_service/blending_plan/tool_radius: 0.01
 * /surface_blending_service/blending_plan/traverse_spd: 0.05
 * /surface_blending_service/publish_region_point_cloud: True
 * /surface_blending_service/robot_scan/cam_tilt_angle: 1.92
 * /surface_blending_service/robot_scan/cam_to_obj_xoffset: 0.2
 * /surface_blending_service/robot_scan/cam_to_obj_zoffset: 0.6
 * /surface_blending_service/robot_scan/group_name: manipulator_asus
 * /surface_blending_service/robot_scan/home_position: home_asus
 * /surface_blending_service/robot_scan/num_scan_points: 10
 * /surface_blending_service/robot_scan/reachable_scan_points_ratio: 1.0
 * /surface_blending_service/robot_scan/scan_target_frame: world_frame
 * /surface_blending_service/robot_scan/scan_topic: sensor_point_cloud
 * /surface_blending_service/robot_scan/stop_on_planning_error: True
 * /surface_blending_service/robot_scan/sweep_angle_end: 1.05
 * /surface_blending_service/robot_scan/sweep_angle_start: 0
 * /surface_blending_service/robot_scan/tcp_frame: asus_frame
 * /surface_blending_service/robot_scan/tcp_to_cam_pose/rx: 0.0
 * /surface_blending_service/robot_scan/tcp_to_cam_pose/ry: 0.0
 * /surface_blending_service/robot_scan/tcp_to_cam_pose/rz: 0.0
 * /surface_blending_service/robot_scan/tcp_to_cam_pose/x: 0.0
 * /surface_blending_service/robot_scan/tcp_to_cam_pose/y: 0.0
 * /surface_blending_service/robot_scan/tcp_to_cam_pose/z: 0.0
 * /surface_blending_service/robot_scan/world_frame: world_frame
 * /surface_blending_service/robot_scan/world_to_obj_pose/rx: 0.0
 * /surface_blending_service/robot_scan/world_to_obj_pose/ry: 0.0
 * /surface_blending_service/robot_scan/world_to_obj_pose/rz: 0.0
 * /surface_blending_service/robot_scan/world_to_obj_pose/x: 0.9
 * /surface_blending_service/robot_scan/world_to_obj_pose/y: 0.4
 * /surface_blending_service/robot_scan/world_to_obj_pose/z: 0.04
 * /surface_blending_service/surface_detection/frame_id: world_frame
 * /surface_blending_service/surface_detection/ignore_largest_cluster: False
 * /surface_blending_service/surface_detection/k_search: 20
 * /surface_blending_service/surface_detection/marker_alpha: 0.6
 * /surface_blending_service/surface_detection/mls_point_density: 100
 * /surface_blending_service/surface_detection/mls_search_radius: 0.04
 * /surface_blending_service/surface_detection/mls_upsampling_radius: 0.01
 * /surface_blending_service/surface_detection/occupancy_threshold: 0.5
 * /surface_blending_service/surface_detection/pa_enabled: True
 * /surface_blending_service/surface_detection/pa_kdtree_radius: 0.016
 * /surface_blending_service/surface_detection/pa_sac_plane_distance: 0.004
 * /surface_blending_service/surface_detection/pa_seg_dist_threshold: 0.008
 * /surface_blending_service/surface_detection/pa_seg_max_iterations: 100
 * /surface_blending_service/surface_detection/rg_curvature_threshold: 2
 * /surface_blending_service/surface_detection/rg_max_cluster_size: 10000
 * /surface_blending_service/surface_detection/rg_min_cluster_size: 100
 * /surface_blending_service/surface_detection/rg_neighbors: 20
 * /surface_blending_service/surface_detection/rg_smoothness_threshold: 0.08
 * /surface_blending_service/surface_detection/stout_mean: 10
 * /surface_blending_service/surface_detection/stout_stdev_threshold: 4.0
 * /surface_blending_service/surface_detection/tabletop_seg_distance_thresh: 0.01
 * /surface_blending_service/surface_detection/tr_max_angle: 3.1
 * /surface_blending_service/surface_detection/tr_max_surface_angle: 0.8
 * /surface_blending_service/surface_detection/tr_min_angle: 0.01
 * /surface_blending_service/surface_detection/tr_mu: 20
 * /surface_blending_service/surface_detection/tr_nearest_neighbors: 400
 * /surface_blending_service/surface_detection/tr_normal_consistency: True
 * /surface_blending_service/surface_detection/tr_search_radius: 0.01
 * /surface_blending_service/surface_detection/use_tabletop_segmentation: False
 * /surface_blending_service/surface_detection/voxel_leaf: 0.004
 * /warehouse_exec: mongod
 * /warehouse_host: localhost
 * /warehouse_port: 33829

NODES
  /
    industrial_robot_simulator (industrial_robot_simulator/industrial_robot_simulator)
    joint_trajectory_action (industrial_robot_client/joint_trajectory_action)
    mongo_wrapper_ros_HP_Compaq_Elite_8300_MT_2344_2433150109357235812 (warehouse_ros/mongo_wrapper_ros.py)
    move_group (moveit_ros_move_group/move_group)
    point_cloud_generator_node (godel_surface_detection/point_cloud_generator_node)
    polygon_offset_node (godel_polygon_offset/godel_polygon_offset_node)
    process_path_generator_node (godel_process_path_generation/process_path_generator_node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    surface_blending_service (godel_surface_detection/surface_blending_service)

auto-starting new master
process[master]: started with pid [2356]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ed99168c-9bcc-11e4-8dc4-7446a09160eb
process[rosout-1]: started with pid [2369]
started core service [/rosout]
process[surface_blending_service-2]: started with pid [2386]
process[point_cloud_generator_node-3]: started with pid [2387]
process[process_path_generator_node-4]: started with pid [2400]
[ INFO] [1421226521.888505978]: waitForService: Service [/offset_polygon] has not been advertised, waiting...
process[polygon_offset_node-5]: started with pid [2415]
[ INFO] [1421226522.003166796]: /offset_polygon ready to service requests.
[ INFO] [1421226522.013710936]: waitForService: Service [/offset_polygon] is now available.
[ INFO] [1421226522.014431112]: /visualize_path_generator ready to service requests.
[ INFO] [1421226522.015021531]: /process_path_generator ready to service requests.
process[rviz-6]: started with pid [2431]
[surface_blending_service-2] process has died [pid 2386, exit code -11, cmd /home/meulage/catkin_ws/devel/lib/godel_surface_detection/surface_blending_service __name:=surface_blending_service __log:=/home/meulage/.ros/log/ed99168c-9bcc-11e4-8dc4-7446a09160eb/surface_blending_service-2.log].
log file: /home/meulage/.ros/log/ed99168c-9bcc-11e4-8dc4-7446a09160eb/surface_blending_service-2*.log
process[industrial_robot_simulator-7]: started with pid [2432]
[ INFO] [1421226522.268047547]: rviz version 1.11.4
[ INFO] [1421226522.268113699]: compiled against OGRE version 1.8.1 (Byatis)
process[joint_trajectory_action-8]: started with pid [2450]
process[robot_state_publisher-9]: started with pid [2497]
/home/meulage/catkin_ws/src/industrial_core/industrial_robot_simulator/industrial_robot_simulator:221: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.joint_state_pub = rospy.Publisher('joint_states', JointState)
/home/meulage/catkin_ws/src/industrial_core/industrial_robot_simulator/industrial_robot_simulator:225: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.joint_feedback_pub = rospy.Publisher('feedback_states', FollowJointTrajectoryFeedback)
/home/meulage/catkin_ws/src/industrial_core/industrial_robot_simulator/industrial_robot_simulator:228: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.robot_status_pub = rospy.Publisher('robot_status', RobotStatus)
process[move_group-10]: started with pid [2531]
[ INFO] [1421226522.587394296]: Loading robot model 'sia20d_workspace'...
[ INFO] [1421226522.588101468]: No root joint specified. Assuming fixed joint
process[mongo_wrapper_ros_HP_Compaq_Elite_8300_MT_2344_2433150109357235812-11]: started with pid [2572]
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
[ INFO] [1421226522.692978524]: Stereo is NOT SUPPORTED
[ INFO] [1421226522.693088964]: OpenGl version: 3 (GLSL 1.3).
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
[ INFO] [1421226522.866515856]: Loading robot model 'sia20d_workspace'...
[ INFO] [1421226522.866569146]: No root joint specified. Assuming fixed joint
[ INFO] [1421226523.019068872]: Loading robot model 'sia20d_workspace'...
[ INFO] [1421226523.019121639]: No root joint specified. Assuming fixed joint
[ INFO] [1421226523.263880680]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1421226523.266277418]: MoveGroup debug mode is OFF
Starting context monitors...
[ INFO] [1421226523.266305895]: Starting scene monitor
[ INFO] [1421226523.268490292]: Listening to '/planning_scene'
[ INFO] [1421226523.268527353]: Starting world geometry monitor
[ INFO] [1421226523.270844918]: Listening to '/collision_object' using message notifier with target frame '/world_frame '
[ INFO] [1421226523.273137153]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1421226523.406103916]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ INFO] [1421226523.518612825]: Initializing OMPL interface using ROS parameters
[ INFO] [1421226523.540729045]: Using planning interface 'OMPL'
[ INFO] [1421226523.615010404]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1421226523.615638661]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1421226523.616166685]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1421226523.616691917]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1421226523.617143954]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1421226523.617550843]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1421226523.617600831]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1421226523.617623325]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1421226523.617640007]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1421226523.617656785]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1421226523.617674403]: Using planning request adapter 'Fix Start State Path Constraints'
[ INFO] [1421226523.948744536]: MoveitSimpleControllerManager: Added FollowJointTrajectory controller for 
[ INFO] [1421226523.948869286]: Returned 1 controllers in list
[ INFO] [1421226523.960644713]: Trajectory execution is managing controllers
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
[ INFO] [1421226524.200133203]: 

********************************************************
* MoveGroup using: 
*     - CartesianPathService
*     - ExecutePathService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
*     - GetPlanningSceneService
********************************************************

[ INFO] [1421226524.200242034]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1421226524.200269802]: MoveGroup context initialization complete

All is well! Everyone is happy! You can start planning now!

[ INFO] [1421226525.109272686]: Initializing RobotBlendingPanel
[ INFO] [1421226525.124670387]: rviz blending panel connecting to services
[ INFO] [1421226525.125492309]: waitForService: Service [/surface_detection] has not been advertised, waiting...
[ INFO] [1421226525.165095958]: rviz RobotBlendingPanel reading config file
[ INFO] [1421226525.165150903]: rviz RobotBlendingPanel Finished reading config file
[ERROR] [1421226527.138558939]: rviz panel could not connect to one or more ros services:
    '/surface_detection'
    '/select_surface'
    '/surface_blending_parameters
[ INFO] [1421226527.138661582]: rviz blending panel connecting to services
[ INFO] [1421226527.139694035]: waitForService: Service [/surface_detection] has not been advertised, waiting...
[ERROR] [1421226529.149731669]: rviz panel could not connect to one or more ros services:
    '/surface_detection'
    '/select_surface'
    '/surface_blending_parameters
[ INFO] [1421226529.149906620]: rviz blending panel connecting to services
[ INFO] [1421226529.151299812]: waitForService: Service [/surface_detection] has not been advertised, waiting...
================================================================================REQUIRED process [rviz-6] has died!
process has died [pid 2431, exit code -11, cmd nice /opt/ros/indigo/lib/rviz/rviz -d /home/meulage/catkin_ws/src/godel/godel_surface_detection/rviz/robot_blending.rviz __name:=rviz __log:=/home/meulage/.ros/log/ed99168c-9bcc-11e4-8dc4-7446a09160eb/rviz-6.log].
log file: /home/meulage/.ros/log/ed99168c-9bcc-11e4-8dc4-7446a09160eb/rviz-6*.log
Initiating shutdown!
================================================================================
[mongo_wrapper_ros_HP_Compaq_Elite_8300_MT_2344_2433150109357235812-11] killing on exit
[move_group-10] killing on exit
[robot_state_publisher-9] killing on exit
[joint_trajectory_action-8] killing on exit
[industrial_robot_simulator-7] killing on exit
[rviz-6] killing on exit
[polygon_offset_node-5] killing on exit
[process_path_generator_node-4] killing on exit
[point_cloud_generator_node-3] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by gavanderhoorn** [comment]
Can you run `surface_blending_service` in GDB? See [How to Roslaunch Nodes in Valgrind or GDB](http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB) for how to do this.

That would give us a stack trace, and possibly somewhere to begin searching.

It may be necessary to rebuild `surface_blending_service` with the `Debug` or `RelWithDebInfo` CMake profiles.

**Comment by gavanderhoorn** [comment]
Not related, but just noticed this:

> the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'

You might want to take care of that (only needed once).

**Comment by shaun-edwards** [comment]
In addition, you mentioned the node only crashes on one of multiple hardware configurations.  Out of curiosity is the one that is crashing a 32bit machine (vs. 64 bit)?

**Comment by AnthonyBaup** [comment]
I work with VictorLamoine.

It crashes on a 64bits machine.
After using gdb it seems the problem comes from pcl :

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3fafc50 in boost::math::lanczos::lanczos_initializer<boost::math::lanczos::lanczos17m64, long double>::init::init() () from /usr/lib/libpcl_sample_consensus.so.1.7

PCL is in version 1.7.1-3 perhaps it is the problem ?

**Comment by gavanderhoorn** [comment]
@AnthonyBaup: could you provide us with a backtrace (`bt <enter>` at the gdb prompt after it has crashed)?

**Comment by AnthonyBaup** [comment]
@gavanderhoorn I tried to reinstall pcl from source (1.8) 
then I recompiled my workspace (godel CMakeList.txt has been modified to use PCL 1.8 and not 1.7 as before) and it worked.
There are no more errors using blending service.
Of cource, I don't have the segmentation fault using gdb anymore.

**Comment by VictorLamoine** [comment]
@AnthonyBaup Please test with PCL release 1.7.2 as well (compile it from sources [here](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.7.2))

PCL 1.7.1 is not the current release, current is 1.7.2.
The error is on PCL side so I guess this can be closed?

**Comment by gavanderhoorn** [comment]
Lets first make sure it was actually an ABI (?) issue.

**Comment by VictorLamoine** [comment]
```
(gdb) bt
#0  0x00007ffff3fd9a70 in boost::math::lanczos::lanczos_initializer<boost::math::lanczos::lanczos17m64, long double>::init::init() ()
   from /usr/lib/libpcl_sample_consensus.so.1.7
#1  0x00007ffff3fb16be in ?? () from /usr/lib/libpcl_sample_consensus.so.1.7
#2  0x00007ffff7dea13a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdae8, env=env@entry=0x7fffffffdaf8) at dl-init.c:78
#3  0x00007ffff7dea223 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:36
#4  _dl_init (main_map=0x7ffff7ffe1c8, argc=1, argv=0x7fffffffdae8, env=0x7fffffffdaf8) at dl-init.c:126
#5  0x00007ffff7ddb30a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#6  0x0000000000000001 in ?? ()
#7  0x00007fffffffdea7 in ?? ()
#8  0x0000000000000000 in ?? ()
```

We are not sure yet but our tests shows that using `libpcl-all` produces the seg fault, using `libpcl-1.7-all` solves it. (PCL trunk works too)

**Comment by AnthonyBaup** [comment]
https://github.com/PointCloudLibrary/pcl/issues/619

**Comment by VictorLamoine** [comment]
I 'm pretty sure the problem is that the code is compiled with C++11 enabled and PCL has an issue with it's binaries and C++11 (see PointCloudLibrary/pcl#619)

Compiling PCL and linking to that compiled version solves the problem.
